"""
文件路径: scripts/extract_image_urls.py
文件作用: 从源报告 Markdown 中抽取图片 URL，生成图表 URL 索引。
主要内容:
- extract_urls_from_text: 抽取 Markdown 图片和原始 http(s) 图片链接
- yaml_quote: 输出安全的 YAML 字符串
- main: 扫描 23 篇源报告并写入 references/chart-notes/image-url-index.yml
依赖关系:
- pathlib
- re
使用场景:
- 更新 chart-notes 前运行，帮助定位源报告图片 URL
注意事项:
- 本脚本只抽取 URL，不下载图片，不验证远端图片是否可访问
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "references" / "source-reports"
OUTPUT_FILE = ROOT / "references" / "chart-notes" / "image-url-index.yml"


MARKDOWN_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\((https?://[^)\s]+)\)")
RAW_IMAGE_RE = re.compile(r"https?://[^\s)\"']+\.(?:png|jpg|jpeg|webp|gif)(?:\?[^\s)\"']*)?", re.IGNORECASE)


def repo_path(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def extract_urls_from_text(text: str) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    seen: set[str] = set()

    for match in MARKDOWN_IMAGE_RE.finditer(text):
        alt_text = match.group(1).strip()
        url = match.group(2).strip()
        if url not in seen:
            seen.add(url)
            results.append((url, alt_text or "markdown image"))

    for match in RAW_IMAGE_RE.finditer(text):
        url = match.group(0).strip()
        if url not in seen:
            seen.add(url)
            results.append((url, "raw image url"))

    return results


def main() -> int:
    source_files = sorted(SOURCE_DIR.glob("*.md"))
    rows: list[tuple[str, str, str]] = []
    for source_file in source_files:
        text = source_file.read_text(encoding="utf-8", errors="replace")
        for url, context in extract_urls_from_text(text):
            rows.append((repo_path(source_file), url, context[:160]))

    lines = [
        "# Generated by scripts/extract_image_urls.py",
        f"source_reports_count: {len(source_files)}",
        f"image_urls_count: {len(rows)}",
        "images:",
    ]
    for source_file, url, context in rows:
        lines.extend(
            [
                f"  - source_file: {yaml_quote(source_file)}",
                f"    url: {yaml_quote(url)}",
                f"    alt_text_or_context: {yaml_quote(context)}",
            ]
        )

    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"source_reports_count={len(source_files)}")
    print(f"image_urls_count={len(rows)}")
    print(f"output={repo_path(OUTPUT_FILE)}")
    if len(source_files) != 23:
        print("error: expected source_reports_count=23")
        return 1
    if not rows:
        print("error: expected at least one image URL")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
